name = "my-app-api"
main = "src/index.ts"
compatibility_date = "2024-04-01"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "my-app-db"
database_id = "bb2b1068-c787-4a1b-8637-3d67353d2dae"
migrations_dir = "drizzle"
